name: overlay
description: "Run e2e-tests on GitHub"
inputs:
  environment-url:
    description: "Application URL of the environment, e.g., `https://overlay-my-repo-pr-1.example.com`"
    required: true
  test-repository:
    description: "GitHub repository with e2e-tests source code"
    default: "nepalevov/ai-dial-chat"
  test-branch:
    description: "Git branch name of the e2e-tests repository"
    default: "development"
  dotenv-file:
    description: "Relative path to dotenv file with configuration variables for e2e-tests in e2e-tests repository. Will be sourced before running tests"
    default: "apps/chat-e2e/.env.ci"
  java-distribution:
    description: "Java distribution"
    default: "temurin"
  java-version:
    description: "Java version"
    default: "17"
  node-version:
    description: "NodeJS version to use"
    default: "lts/*"
  playwright-version:
    description: "Playwright version"
    default: "latest"
  allure-version:
    description: "Allure Report version"
    default: "2.24.0"
  report-prefix:
    description: "Test report name prefix"
    default: ${{ github.run_id }}
  working-directory:
    description: "Working directory to run tests in"
    default: "tests"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: ${{ inputs.test-repository }}
        ref: ${{ inputs.test-branch }}
        path: ${{ inputs.working-directory }}
        lfs: true
        persist-credentials: false
    - uses: falti/dotenv-action@a33be0b8cf6a6e6f1b82cc9f3782061ab1022be5 # v1.1.4
      with:
        path: "${{ inputs.working-directory }}/${{ inputs.dotenv-file }}"
        log-variables: true
        export-variables: true
        keys-case: bypass
    - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: ${{ inputs.node-version }}
    - uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
    - name: Install Allure CLI
      run: |
        curl -fsSL --retry 5 --retry-delay 2 https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure_${ALLURE_VERSION}-1_all.deb -o /tmp/allure.deb
        sudo dpkg -i /tmp/allure.deb
        echo "Allure CLI version: $(allure --version)"
      shell: bash
      env:
        ALLURE_VERSION: ${{ inputs.allure-version }}
    - name: Install Playwright
      run: |
        npm install -D @playwright/test@${{ inputs.playwright-version }} allure-playwright
        npx playwright install --with-deps
        echo "Playwright version: $(npx playwright --version)"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        ENVIRONMENT_URL: ${{ inputs.environment-url }}
    - run: echo $E2E_USERNAME
      shell: bash
    - name: Run tests
      run: |
        echo "URL to run overlay e2e tests against:         ${NEXT_PUBLIC_OVERLAY_HOST}"
        echo "Config for arithmetic e2e api tests:          ${ENTITY_ARITHMETIC_REQUEST_FOR_API_TESTS}"
        echo "Config for attachment request e2e api tests:  ${ENTITY_PLUS_ATTACHMENT_FOR_API_TESTS}"
        echo "Config for attachment response e2e api tests: ${ENTITY_SIMPLE_REQUEST_FOR_API_TESTS}"
        echo "Simple requests model for e2e tests:          ${SIMPLE_REQUEST_MODEL}"
        npx nx run chat-e2e:e2e:overlay --configuration=production --output-style=stream --skipInstall
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        E2E_ADMIN: ${{ env.E2E_ADMIN }}
        E2E_OVERLAY_USERNAME: ${{ env.E2E_OVERLAY_USERNAME }}
        E2E_PASSWORD: ${{ env.E2E_PASSWORD }}
        NEXT_PUBLIC_OVERLAY_HOST: ${{ inputs.environment-url }}
        NEXT_PUBLIC_OVERLAY_USER_BUCKET: ${{ env.NEXT_PUBLIC_OVERLAY_USER_BUCKET }}
    - name: Generate Allure Report
      if: ${{ !cancelled() }}
      run: |
        allure generate ./apps/chat-e2e/allure-overlay-results -o ./apps/chat-e2e/allure-overlay-report --clean
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Upload Allure Report
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      if: ${{ !cancelled() }}
      with:
        name: "${{ inputs.report-prefix }}-overlay"
        path: |
          ${{ inputs.working-directory }}/apps/chat-e2e/allure-overlay-report
        retention-days: 30
